name: Server Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check_fmt_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
    - uses: actions/checkout@master
    - name: fmt
      run: cargo fmt --all -- --check

  build_test_server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres

    services:
          postgres:
            image: postgres:12
            env:
              POSTGRES_USER: postgres
              POSTGRES_PASSWORD: postgres
              POSTGRES_DB: postgres
            ports:
              # will assign a random free host port
                - 5432:5432
            # needed because the postgres container does not provide a healthcheck
            options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5


    steps:
    - uses: actions/checkout@v2

    - name: Install sqlx-cli
      uses: actions-rs/install@v0.1
      with:
        crate: sqlx-cli
        version: latest
        use-tool-cache: true

    - name: Cache
      uses: actions/cache@v2.1.4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Migrate
      run: sqlx migrate run

    - name: Check sqlx-data
      run: cargo sqlx prepare --check

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
